### ISSUE TITLE
this.router.filter is not a function

### ISSUE THREAD

**Issue by bcorcoran** [sbine/nova-route-viewer#12]
Laravel 6.3.0
Laravel Nova 2.5.0
PHP 7.3

I'm getting a javascript error when attempting to view the Router Viewer. I get no results (I can successfully see them using `php artisan route:list` and this.router.filter is not a function error in the browser console.

**Comment by sbine** [comment]
The route viewer code doesn't contain any instances of `this.router.filter`. The closest is [`this.routes.filter`](https://github.com/sbine/nova-route-viewer/blob/master/resources/js/components/Tool.vue#L125), but since `this.routes` is instantiated to an empty array, the `filter` function should always be available.

Can you provide a stack trace, and the full line or section of code causing the error?

**Comment by bcorcoran** [comment]
Well, I don't have dev mode enabled on Nova, but:

![Screen Shot 2019-10-24 at 00 40 42](https://user-images.githubusercontent.com/313697/67454114-05876f80-f5f7-11e9-8cb2-8cd9c1f8ecfc.png)

If you can tell me what you'd like me to try, I'm happy to try it, but I don't have a lot of time to debug at the moment.

**Comment by bcorcoran** [comment]
Actually I just looked again and ran `Nova.request().get('/nova-vendor/route-viewer/routes').then(response => { console.log(response.data) })` in the console and it gave me my index page... meaning the routes aren't working properly. The route is listed in `php artisan route:list` but I suspect there's something going on with `Sbine\RouteViewer\Http\Controllers\Api@getRoutes`

**Comment by sbine** [comment]
Two things that could help:
1. Check the Network tab to see what the HTTP status code and/or error message was on the failed request to `/nova-vendor/route-viewer/routes`
2. Check your Laravel application log (usually `storage/logs/laravel.log`) for an error message

**Comment by bcorcoran** [comment]
OK, disregard this. I am running an SPA and I had the following rule:

```
Route::any('{all}', function() { return view('index'); })
    ->middleware('auth')
    ->where(['all' => '^(?!admin|nova-api).*$']);
```

I added `nova-vendor` to the list of exceptions and it's working just fine. Sorry for the trouble!
