### ISSUE TITLE
Update button & some on the arrays

### ISSUE THREAD

**Issue by antonioribeiro** [sbine/nova-route-viewer#4]
I probably need an update button on it, for now I'm just clicking on a different tool and then getting back to route viewer, but I, then, have to filter what I was watching again.

You could also simplify those arrays a bit, IMO:

```
GET, HEAD
```

is easier to read than

```
[ "GET", "HEAD" ]
```

But I also like [the colouring approach](https://github.com/garygreen/pretty-routes):

![image](https://user-images.githubusercontent.com/3182864/45003038-369c7f00-afb4-11e8-99c6-9275ab58a74c.png)

Nice package, by the way, thanks for creating it!

**Comment by sbine** [comment]
This is a great idea! Someone on [Twitter](https://twitter.com/Skyrpex/status/1033463890246623233) suggested it as well. I'm happy to accept a PR for this, or will work on it myself when I have some time.

**Comment by antonioribeiro** [comment]
Partially done in https://github.com/sbine/nova-route-viewer/pull/5
