### ISSUE TITLE
Helper functions are no longer added by default

### ISSUE THREAD

**Issue by rickgoemans** [sbine/nova-route-viewer#9]
In Laravel 6 helper functions (like ends_with) are no longer available by default.

Since your controller (Api.php) uses ends_with you'll receive an error on new Laravel installations.

Solution:
1. (Preferred) use the following instead:
`Illuminate\Support\Str::endsWith($haystack, $needles);`

2. Add dependency: `laravel/helpers`.

**Comment by rickgoemans** [comment]
Here you can read Laravel's new upgrade guide regaring the matter:
[Laravel 6 Upgrade guide](https://laravel.com/docs/6.x/upgrade#helpers)

**Comment by sbine** [comment]
Fixed in #11.
